"""
Django settings for TradeMind.

Generated by Django 4.2. | Built for SDG 3 | Hackathon-Ready
"""
import os
from pathlib import Path
from dotenv import load_dotenv

# Load environment variables from .env
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-9z&f+8yjv1a-3m#r^xq2w_+k8n!l2m3p4o5i6u7y8t9r0e1w2q')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'True') == 'True'

# Update this in production
ALLOWED_HOSTS = [
    '127.0.0.1',
    'localhost',
    'trademindjournal.onrender.com',  # For Render deployment
]

CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'trade-mind-unique',
    }
}

# --- PROJECT CONFIG ---
# Add your custom settings here
TRADER_TYPES = [
    ('day', 'Day Trader'),
    ('swing', 'Swing Trader'),
    ('scalper', 'Scalper'),
]

EMOTION_CHOICES = [
    ('fear', '😨 Fear'),
    ('angry', '😡 Angry'),
    ('sad', '😢 Sad'),
    ('neutral', '😐 Neutral'),
    ('happy', '😊 Happy'),
    ('chill', '🧘‍♂️ Chill'),
]

# --- APPS ---
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'trademind_app.apps.TrademindAppConfig',  # Use AppConfig
    
    # Local app
    #'trademind_app',
]

# --- MIDDLEWARE ---
# Security + Session + CSRF built-in
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# --- URL CONFIG ---
ROOT_URLCONF = 'core.urls'

# --- TEMPLATES ---
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                # Custom context: pass dark_mode or user theme
                'trademind_app.context_processors.theme_context',
            ],
        },
    },
]

# --- WSGI ---
WSGI_APPLICATION = 'core.wsgi.application'

# --- DATABASE ---
# SQLite for rapid prototyping (hackathon-ready)
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# --- PASSWORD VALIDATION ---
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {
            'min_length': 8,
        }
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# --- INTERNATIONALIZATION ---
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'Africa/Nairobi'  # Trader-relevant timezone
USE_I18N = True
USE_TZ = True

# --- STATIC FILES (CSS, JS, Images) ---
# https://docs.djangoproject.com/en/4.2/howto/static-files/
STATIC_URL = '/static/'
STATICFILES_DIRS = [
    BASE_DIR / 'static',  # Where you store your CSS, JS, images
]
STATIC_ROOT = BASE_DIR / 'staticfiles'  # Collected for production

# --- MEDIA FILES (User uploads) ---
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# --- DEFAULT PRIMARY KEY ---
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# --- CUSTOM CONTEXT PROCESSOR (for theme support) ---
# We'll create this in trademind_app/context_processors.py
# Allows templates to know if user prefers dark/light mode

# Redirect after logout
LOGOUT_REDIRECT_URL = 'trademind_app:landing'